import React from "react";
import Link from "next/link";
import { motion } from "framer-motion";
import { FiArrowLeft, FiFileText, FiLock } from "react-icons/fi";

export type LegalDocumentType = "terms" | "privacy" | "about";

const contactEmail = "asapgrouphq@gmail.com";
const updatedDate = "1 October, 2026";

const documentMetadata: Record<
  LegalDocumentType,
  { title: string; label: string; updated?: string }
> = {
  terms: {
    title: "Terms of Service",
    label: "Legal & compliance",
    updated: updatedDate,
  },
  privacy: {
    title: "Privacy Policy",
    label: "Your privacy",
    updated: updatedDate,
  },
  about: { title: "About ChopBeta", label: "Our purpose" },
};

function TermsContent() {
  return (
    <>
      <h2>1. Introduction and Acceptance</h2>
      <p>
        These Terms of Service ("Terms") govern your access to and use of the
        Chopbeta web application and any related websites and services
        (together, the "Service"). The Service is operated by{" "}
        <strong>ASAP GROUPS</strong> located at LAGOS, NIGERIA("Chopbeta", "we",
        "us", "our").
      </p>
      <p>
        By creating an account or using the Service, you agree to these Terms
        and to our{" "}
        <span
          className="font-semibold text-[#1E6B3C]"
        >
          Privacy Policy
        </span>
        . If you do not agree, please do not use the Service.
      </p>

      <h2>2. About the Service</h2>
      <p>
        Chopbeta helps students and young adults manage their food spending
        through expense tracking, budget monitoring, spending reminders, and
        personalised meal recommendations.
      </p>

      <h2>3. Eligibility</h2>
      <p>
        You must be <strong>at least 16 years old</strong> to create an account
        and use the Service. By registering, you confirm that you meet this
        requirement and that you have the legal capacity to agree to these
        Terms.
      </p>

      <h2>4. Your Account</h2>
      <ul>
        <li>
          You agree to provide accurate, current, and complete information when
          you register and to keep it up to date.
        </li>
        <li>
          You are responsible for keeping your login credentials confidential
          and for all activity that takes place under your account.
        </li>
        <li>
          Notify us promptly at{" "}
          <a
            href={`mailto:${contactEmail}`}
            className="text-[#1E6B3C] underline"
          >
            {contactEmail}
          </a>{" "}
          if you suspect unauthorised access to your account.
        </li>
        <li>
          You may not share, sell, or transfer your account to anyone else.
        </li>
      </ul>

      <h2>5. Acceptable Use</h2>
      <p>
        You agree to use Chopbeta only for lawful, personal, non-commercial
        purposes. You must not:
      </p>
      <ul>
        <li>
          Use the Service in violation of any applicable law or regulation.
        </li>
        <li>
          Provide false or misleading information, or impersonate another
          person.
        </li>
        <li>
          Attempt to gain unauthorised access to the Service, other users'
          accounts, or our systems or data.
        </li>
        <li>
          Interfere with or disrupt the Service, including by introducing
          malware or sending excessive automated requests.
        </li>
        <li>
          Copy, scrape, reverse engineer, or extract data or source code from
          the Service, except as permitted by law.
        </li>
        <li>
          Use the Service, or data obtained from it, to build a competing
          product.
        </li>
      </ul>
      <p>We may suspend or terminate accounts that violate this section.</p>

      <h2>6. Recommendations and Information Are Not Professional Advice</h2>
      <p>
        <strong>Financial Information.</strong> Budget allocations, expense
        summaries, spending insights, and reminders are provided for personal
        planning only. They are not financial, investment, tax, or legal advice,
        and you remain responsible for your own financial decisions.
      </p>
      <p>
        <strong>Nutritional Information and Meal Recommendations.</strong> Meal
        suggestions are generated by algorithms using the information you
        provide and general meal data. They are estimates intended for planning
        and discovery. They are not medical advice or certified nutritional or
        dietary advice. Nutritional values, portion sizes, and prices are
        approximate and vary by location, vendor, and time.
      </p>
      <p>
        <strong>Allergies and Health Conditions.</strong> Chopbeta does not
        verify ingredients or allergens. If you have allergies, a medical
        condition, or specific dietary needs, check meal ingredients yourself
        and consult a qualified health professional before relying on any
        suggestion.
      </p>

      <h2>7. Your Content</h2>
      <p>
        "Your Content" means the information and material you submit through the
        Service, such as expense entries, budget settings, meal preferences, and
        meal ratings.
      </p>
      <ul>
        <li>You keep ownership of Your Content.</li>
        <li>
          You grant us a non-exclusive, worldwide, royalty-free licence to
          store, process, and use Your Content to operate, maintain, and improve
          the Service, including in anonymised or aggregated form, as described
          in our Privacy Policy.
        </li>
        <li>
          You confirm that you have the right to submit Your Content and that it
          does not violate any law or third-party rights.
        </li>
      </ul>

      <h2>8. Intellectual Property</h2>
      <p>
        The Service, including its software, design, logos, name, text, meal
        database, and recommendation logic, is owned by Chopbeta or its
        licensors and is protected by intellectual property laws. We grant you a
        limited, personal, non-exclusive, non-transferable, revocable licence to
        use the app for its intended purpose. All rights not expressly granted
        are reserved.
      </p>

      <h2>9. Third-Party Services</h2>
      <p>
        The Service may rely on third-party providers, such as hosting,
        authentication, analytics, and notification services. We are not
        responsible for third-party services, and your use of any of them may be
        subject to their own terms.
      </p>

      <h2>10. Availability, Updates, and Changes to the Service</h2>
      <p>
        We work to keep the Service reliable, but we do not guarantee
        uninterrupted or error-free operation. We may update, modify, suspend,
        or discontinue features from time to time, for example for maintenance,
        security, or improvements. Where a change is material and adversely
        affects you, we will give reasonable notice where practicable.
      </p>

      <h2>11. Termination and Account Deletion</h2>
      <ul>
        <li>
          You may stop using the Service and delete your account at any time
          through Settings &gt; Account &gt; Delete Account in the app, or by
          emailing{" "}
          <a
            href={`mailto:${contactEmail}`}
            className="text-[#1E6B3C] underline"
          >
            {contactEmail}
          </a>
          .
        </li>
        <li>
          We may suspend or terminate your access if you breach these Terms, if
          required by law, or if we discontinue the Service.
        </li>
        <li>
          When your account is deleted, your personal data will be handled as
          described in the Privacy Policy. Provisions that by their nature
          should survive termination, including intellectual property,
          disclaimers, limitation of liability, and governing law, will continue
          to apply.
        </li>
      </ul>

      <h2>12. Disclaimers</h2>
      <p>
        To the fullest extent permitted by law, the Service is provided "as is"
        and "as available", without warranties of any kind, express or implied,
        including warranties of accuracy, fitness for a particular purpose, and
        non-infringement. We do not warrant that recommendations, prices, or
        nutritional information will be accurate, complete, or suitable for you.
      </p>

      <h2>13. Limitation of Liability</h2>
      <p>
        To the fullest extent permitted by law, Chopbeta and its directors,
        employees, and partners will not be liable for any indirect, incidental,
        special, or consequential loss, or for loss of data, income, or
        opportunity, arising from your use of, or inability to use, the Service.
      </p>
      <p>
        Nothing in these Terms excludes or limits liability that cannot be
        excluded or limited under applicable law, including for fraud or wilful
        misconduct.
      </p>

      <h2>14. Indemnity</h2>
      <p>
        You agree to indemnify and hold Chopbeta harmless from claims, losses,
        and reasonable expenses arising from your breach of these Terms or your
        misuse of the Service.
      </p>

      <h2>15. Changes to These Terms</h2>
      <p>
        We may update these Terms from time to time. For material changes, we
        will notify you through the app or by email at least 14 days before they
        take effect. If you continue using the Service after the effective date,
        you accept the updated Terms. If you do not agree, you may delete your
        account.
      </p>

      <h2>16. General</h2>
      <p>
        These Terms and the Privacy Policy form the entire agreement between you
        and Chopbeta regarding the Service. If any provision is found
        unenforceable, the remainder stays in effect. Our failure to enforce a
        right is not a waiver of it. You may not assign your rights under these
        Terms without our consent.
      </p>

      <h2>17. Contact Us</h2>
      <p>
        <strong>ASAP GROUPS</strong>
        <br />
        Email:{" "}
        <a href={`mailto:${contactEmail}`} className="text-[#1E6B3C] underline">
          {contactEmail}
        </a>
        <br />
        Address: LAGOS, NIGERIA
      </p>
    </>
  );
}

function PrivacyContent() {
  return (
    <>
      <h2>1. Introduction</h2>
      <p>
        At Chopbeta, we respect your privacy and are committed to protecting
        your personal data. This Privacy Policy explains what personal data we
        collect through the Chopbeta mobile app and related services (the
        "Service"), why we collect it, how we use, share, and protect it, and
        the choices and rights you have.
      </p>
      <p>
        This policy is designed to comply with the{" "}
        <strong>Nigeria Data Protection Act 2023 (NDPA)</strong>.
      </p>

      <h2>2. Who Is Responsible for Your Data</h2>
      <p>
        The data controller is <strong>ASAP GROUPS</strong>, LAGOS, NIGERIA
        ("Chopbeta", "we", "us").
      </p>
      <p>
        <strong>Privacy contact:</strong> ASAP GROUPS
        <br />
        <strong>Email:</strong>{" "}
        <a href={`mailto:${contactEmail}`} className="text-[#1E6B3C] underline">
          {contactEmail}
        </a>
      </p>

      <h2>3. Personal Data We Collect</h2>
      <p>
        <strong>Account Data.</strong> Name, email address, and password (stored in hashed form, never in plain
        text).
      </p>
      <p>
        <strong>Profile and Demographic Data.</strong> Age group, living
        arrangement (for example, on-campus, off-campus, or with family), and
        monthly income or allowance range, state, institution, location.
      </p>
      <p>
        <strong>Behavioural and Financial Inputs You Provide.</strong> Food
        spending entries, budget amounts and thresholds, and logged meal
        choices, preferences, and ratings. These are entered by you. Chopbeta
        does not connect to your bank accounts or access your bank or card
        details.
      </p>
      <p>
        <strong>Technical and Usage Data.</strong> App interaction logs, device
        type and model, operating system and app version, IP address, crash and
        performance data, feature usage patterns, and push notification token if
        you enable spending reminders.
      </p>
      <p>
        We do not intentionally collect sensitive personal data (such as health
        records, biometric data, religious beliefs, or political opinions).
        Please do not enter such information in free-text fields.
      </p>

      <h2>4. How and Why We Use Your Data</h2>
      <div className="mb-5 overflow-x-auto rounded-xl border border-gray-100">
        <table className="w-full min-w-[560px] border-collapse text-left text-sm">
          <thead className="bg-[#F3F8F4]">
            <tr>
              <th className="p-3 border-b">Purpose</th>
              <th className="p-3 border-b">Data used</th>
              <th className="p-3 border-b">Lawful basis (NDPA)</th>
            </tr>
          </thead>
          <tbody>
            <tr className="border-b">
              <td className="p-3">
                Create and manage your account and authenticate you
              </td>
              <td className="p-3">Account data</td>
              <td className="p-3">Performance of a contract</td>
            </tr>
            <tr className="border-b">
              <td className="p-3">
                Provide expense tracking and budget calculations
              </td>
              <td className="p-3">Profile, financial and behavioural inputs</td>
              <td className="p-3">Performance of a contract</td>
            </tr>
            <tr className="border-b">
              <td className="p-3">
                Generate personalised meal recommendations matched to your
                budget and preferences
              </td>
              <td className="p-3">Profile, budget, preferences, ratings</td>
              <td className="p-3">Performance of a contract</td>
            </tr>
            <tr className="border-b">
              <td className="p-3">Send spending alerts and reminders</td>
              <td className="p-3">Budget data, notification token</td>
              <td className="p-3">
                Performance of a contract / consent (push notifications)
              </td>
            </tr>
            <tr className="border-b">
              <td className="p-3">
                Analyse aggregated and anonymised trends to improve performance
                and develop features
              </td>
              <td className="p-3">
                Behavioural and usage data (aggregated or anonymised)
              </td>
              <td className="p-3">Legitimate interest</td>
            </tr>
            <tr className="border-b">
              <td className="p-3">
                Keep the Service secure and prevent fraud or abuse
              </td>
              <td className="p-3">Technical and usage data</td>
              <td className="p-3">Legitimate interest / legal obligation</td>
            </tr>
            <tr className="border-b">
              <td className="p-3">
                Respond to your requests and support enquiries
              </td>
              <td className="p-3">Account data, communications</td>
              <td className="p-3">
                Performance of a contract / legitimate interest
              </td>
            </tr>
            <tr>
              <td className="p-3">Comply with legal obligations</td>
              <td className="p-3">As required</td>
              <td className="p-3">Legal obligation</td>
            </tr>
          </tbody>
        </table>
      </div>
      <p>
        Where we rely on consent, you can withdraw it at any time (for example,
        by turning off notifications), without affecting earlier processing.
      </p>
      <p>
        <strong>Automated Recommendations.</strong> Meal suggestions and
        spending insights are generated by automated logic using the information
        above. They do not produce legal or similarly significant effects on
        you.
      </p>

      <h2>5. Sharing Your Data</h2>
      <p>
        <strong>We never sell your personal data.</strong> We do not share it
        with advertisers or use it for third-party advertising.
      </p>
      <p>We share personal data only with:</p>
      <ul>
        <li>
          Service providers who process data on our behalf under contract and
          only for the purposes we specify, such as cloud hosting provider,
          database provider, authentication provider, analytics provider, push
          notification provider, and email provider.
        </li>
        <li>
          Authorities or courts, where required by law or to protect rights and
          safety.
        </li>
        <li>
          Professional advisers such as lawyers and auditors, where necessary.
        </li>
        <li>
          A successor, if Chopbeta is involved in a merger, acquisition, or
          transfer of assets, with notice to you of any change of control of
          your data.
        </li>
      </ul>
      <p>
        <strong>Aggregated and Anonymised Data.</strong> We may use data that
        has been aggregated or anonymised so that it no longer identifies you to
        evaluate overall user trends and refine our algorithms. Anonymised data
        is not personal data.
      </p>

      <h2>6. International Transfers</h2>
      <p>
        Some of our service providers may store or process data outside Nigeria.
        Where personal data is transferred abroad, we ensure it is protected as
        required by the NDPA, for example through transfers to countries with
        adequate protection, appropriate contractual safeguards, or your consent
        where applicable.
      </p>

      <h2>7. Data Security</h2>
      <p>
        We use appropriate technical and organisational measures to protect your
        data, including encryption of data in transit (HTTPS), encryption or
        secure storage of data at rest, hashed passwords, role-based access
        controls, and regular backups. No system is completely secure, so we
        cannot guarantee absolute security.
      </p>
      <p>
        If a personal data breach is likely to result in a risk to your rights
        and freedoms, we will notify the Nigeria Data Protection Commission
        (NDPC) within 72 hours of becoming aware of it and will notify affected
        users without undue delay where required by law.
      </p>

      <h2>8. Data Retention</h2>
      <p>
        We keep personal data only as long as necessary for the purposes
        described in this policy:
      </p>
      <ul>
        <li>
          <strong>Account and profile data:</strong> while your account is
          active, and deleted or anonymised within 30 days after you delete your
          account.
        </li>
        <li>
          <strong>Budget, expense, and meal-log data:</strong> deleted or
          anonymised together with your account.
        </li>
        <li>
          <strong>Technical logs:</strong> up to 12 months.
        </li>
        <li>
          <strong>Records required by law:</strong> for the period required by
          law.
        </li>
      </ul>
      <p>
        Aggregated or anonymised data that cannot identify you may be kept
        longer.
      </p>

      <h2>9. Your Rights and Controls</h2>
      <p>
        You control your personal data. Under the NDPA you have the right to:
      </p>
      <ul>
        <li>Be informed about how your data is used.</li>
        <li>Access the personal data we hold about you.</li>
        <li>Correct inaccurate or incomplete data.</li>
        <li>Delete your data, in certain circumstances.</li>
        <li>Restrict or object to certain processing.</li>
        <li>
          Data portability: receive your data in a structured, commonly used
          format.
        </li>
        <li>
          Withdraw consent at any time where processing relies on consent.
        </li>
      </ul>

      <p>
        <strong>How to Exercise Your Rights:</strong>
      </p>
      <ul>
        <li>
          <strong>In the App:</strong> Update or correct your details under
          Settings &gt; Personal Details, and delete your account and associated
          data under Settings &gt; Support &gt; Contact Us &gt; Send an email
          for account termination.
        </li>
        <li>
          <strong>By Email:</strong> Contact{" "}
          <a
            href={`mailto:${contactEmail}`}
            className="text-[#1E6B3C] underline"
          >
            {contactEmail}
          </a>{" "}
          with your request. We may need to verify your identity, and we aim to
          respond within 14 days.
        </li>
        <li>
          <strong>Account Deletion Without the App:</strong> Email{" "}
          <a
            href={`mailto:${contactEmail}`}
            className="text-[#1E6B3C] underline"
          >
            {contactEmail}
          </a>{" "}
          from your registered address.
        </li>
      </ul>
      <p>
        You also have the right to complain to the{" "}
        <a
          href="https://ndpc.gov.ng"
          target="_blank"
          rel="noreferrer"
          className="text-[#1E6B3C] underline"
        >
          Nigeria Data Protection Commission (NDPC)
        </a>
        . We would appreciate the chance to address your concerns first.
      </p>

      <h2>10. Children's Privacy</h2>
      <p>
        Chopbeta is intended for users aged 16 and over. We do not knowingly
        collect personal data from anyone under 16. If you believe a child has
        provided us with personal data, contact{" "}
        <a href={`mailto:${contactEmail}`} className="text-[#1E6B3C] underline">
          {contactEmail}
        </a>{" "}
        and we will delete it promptly.
      </p>

      <h2>11. Cookies and Similar Technologies</h2>
      <p>
        We use essential cookies to keep you signed in and, with your consent,
        analytics cookies to understand usage. You can manage cookies in your
        browser or through our cookie preferences.
      </p>

      <h2>12. Third-Party Links</h2>
      <p>
        The Service may link to third-party websites or services. We are not
        responsible for their privacy practices, so please review their
        policies.
      </p>

      <h2>13. Changes to This Policy</h2>
      <p>
        We may update this policy from time to time. For material changes, we
        will notify you in the app or by email before they take effect, and
        update the "Last updated" date above.
      </p>

      <h2>14. Contact Us</h2>
      <p>
        <strong>ASAP GROUPS</strong>
        <br />
        Email:{" "}
        <a href={`mailto:${contactEmail}`} className="text-[#1E6B3C] underline">
          {contactEmail}
        </a>
        <br />
        Address: LAGOS, NIGERIA
      </p>
    </>
  );
}

function AboutContent() {
  return (
    <>
      <p className="text-base font-semibold text-[#1E6B3C]">
        Smart food budgeting and meal insights for students and young adults.
      </p>
      <p>
        ChopBeta is a student-focused budgeting app built to help you make
        smarter, stress-free decisions about what you spend on food. Managing
        your food money shouldn&apos;t be complicated or overwhelming.
      </p>
      <p>
        By combining simple expense tracking with budget-friendly meal
        recommendations that fit your daily life, ChopBeta makes it easier to
        manage food costs on and off campus.
      </p>
      <h2>What You Can Do</h2>
      <ul>
        <li>
          <strong>Track your spending:</strong> Log and monitor your food
          expenses in real time.
        </li>
        <li>
          <strong>Stay on budget:</strong> Set spending targets and get timely
          reminders as you approach your limits.
        </li>
        <li>
          <strong>Discover affordable meals:</strong> Find practical meal
          options that match your budget and preferences.
        </li>
        <li>
          <strong>Build better habits:</strong> Use insights from your spending
          patterns to stretch your money further.
        </li>
      </ul>
      <h2>Our Promise</h2>
      <ul>
        <li>
          <strong>Your data stays yours.</strong> We never sell your personal
          data.
        </li>
        <li>
          <strong>You are in control.</strong> You can update your information
          or request account deletion at any time.
        </li>
        <li>
          <strong>Built for real student life.</strong> Our recommendations are
          designed around real budgets and everyday meals.
        </li>
      </ul>
      <p>
        Our goal is simple: to make food budgeting practical, accurate, and
        accessible for every student.
      </p>
      <h2>Get in Touch</h2>
      <p>
        Questions, feedback, or suggestions? We&apos;d love to hear from you.
        <br />
        Email: <a href={`mailto:${contactEmail}`}>{contactEmail}</a>
        <br />
        ChopBeta is operated by ASAP GROUPS.
      </p>
    </>
  );
}

export default function LegalDocumentContent({
  document,
  embedded = false,
}: {
  document: LegalDocumentType;
  embedded?: boolean;
}) {
  const meta = documentMetadata[document];
  const content =
    document === "terms" ? (
      <TermsContent />
    ) : document === "privacy" ? (
      <PrivacyContent />
    ) : (
      <AboutContent />
    );

  return (
    <motion.article
      key={document}
      initial={{ opacity: 0, y: 10 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.3, ease: "easeOut" }}
      className={
        embedded
          ? "min-w-0"
          : "mx-auto min-h-screen max-w-5xl bg-[#F8FAFC] px-4 py-6 font-sans text-[#1A2E35] sm:px-6 sm:py-10"
      }
    >
      <div className={embedded ? "" : "mx-auto max-w-4xl"}>
        {!embedded && (
          <div className="mb-5 flex items-center justify-between gap-3">
            <Link
              href="/"
              className="inline-flex min-h-10 items-center gap-2 rounded-xl border border-gray-200 bg-white px-3 text-sm font-semibold text-gray-600 transition hover:border-emerald-200 hover:text-[#1E6B3C]"
            >
              ← Back
            </Link>
            <Link
              href="/signup"
              className="text-sm font-bold text-[#1E6B3C] transition hover:text-[#185A31]"
            >
              Create account
            </Link>
          </div>
        )}
        <div className="overflow-hidden rounded-3xl border border-gray-100 bg-white shadow-[0_12px_36px_rgba(26,46,53,0.06)]">
          <header className="border-b border-gray-100 bg-linear-to-r from-[#F3F8F4] to-white px-5 py-6 sm:px-8 sm:py-8">
            <p className="text-[10px] font-black uppercase tracking-[0.18em] text-[#1E6B3C]">
              {meta.label}
            </p>
            <h1 className="mt-2 text-2xl font-black leading-tight text-[#1A2E35] sm:text-3xl">
              {meta.title}
            </h1>
            {meta.updated && (
              <p className="mt-2 text-xs font-medium text-gray-500">
                Last updated {meta.updated}
              </p>
            )}
            <nav
              aria-label="Company documents"
              className="mt-5 flex flex-wrap gap-2"
            ></nav>
          </header>
          <div className="px-5 py-7 sm:px-8 sm:py-10">
            <div className="legal-document-content space-y-0 text-sm leading-7 text-gray-600 [&_h2]:mb-3 [&_h2]:mt-9 [&_h2]:border-b [&_h2]:border-gray-100 [&_h2]:pb-2 [&_h2]:text-lg [&_h2]:font-extrabold [&_h2]:text-[#1A2E35] [&_p]:mb-4 [&_ul]:mb-5 [&_ul]:ml-5 [&_ul]:list-disc [&_ul]:space-y-2 [&_li]:pl-1 [&_a]:font-semibold [&_a]:text-[#1E6B3C] [&_a]:underline [&_a]:underline-offset-2 [&_strong]:font-bold [&_strong]:text-[#263B30]">
              {content}
            </div>
          </div>
          <footer className="border-t border-gray-100 px-5 py-4 text-xs leading-relaxed text-gray-400 sm:px-8">
            Contact{" "}
            <a
              href={`mailto:${contactEmail}`}
              className="font-semibold text-[#1E6B3C]"
            >
              {contactEmail}
            </a>{" "}
            with questions about this document.
          </footer>
        </div>
      </div>
    </motion.article>
  );
}
